### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by grtcdr** [0-wiz-0/rust-envsys#1]
Any plans to license this example or turn it into a library? I have a project that supports NetBSD and displays battery information and would like to use this code :)

**Comment by 0-wiz-0** [comment]
Sure! I just added the cc0-1.0-universal license in LICENSE - you can do whatever you want with it.
If you prefer a different license, just let me know, this is the most liberal one I know.

**Comment by grtcdr** [comment]
Works for me!

Thank you so much :)

**Comment by 0-wiz-0** [comment]
I've added some basic parsing code as well and described the format a bit. I hope this helps!

Btw, how did you find this project?

**Comment by grtcdr** [comment]
Through a friend, pin :)

He's been helping out since day one when it comes to anything NetBSD-related, and he recommended I check this out.
